Us189 task197
Rephaelbj/iot_configurator pull request #80
Opened 2022-04-19 04:14 UTC by Rephaelbj

2022-04-19 16:23 UTC, GianniConsiglio approved these changes
Works great I like the new changes

2022-04-19 23:51 UTC, ntrobin1 requested changes

2022-04-19 23:51 UTC, ntrobin1 commented on configurator/src/test/org/picmg/test/integrationTest/TestMaker/Test.java
> +            delay = 0;
This should be removed as we do not want default 0 delay (i.e. this will always write over 1000).

2022-04-19 23:51 UTC, ntrobin1 commented on configurator/src/main/resources/testMakerGUI.fxml
> +    <SplitPane dividerPositions="0.2728285077951002, 0.5" focusTraversable="true" prefHeight="583.0" prefWidth="801.0" VBox.vgrow="ALWAYS">
The right pane is statically sized and fine, but the left side of this is finnicky. It resizes the window but the content does not change and leaves a bunch of white space.

2022-04-19 23:51 UTC, ntrobin1 commented on configurator/src/test/org/picmg/test/integrationTest/TestMaker/Test.java
> +        public Step()
I don't think this is a safe constructor. I see this is used and then given data with fromJson - why not make a constructor that takes the json object instead.

2022-04-19 23:51 UTC, ntrobin1 commented on configurator/src/test/org/picmg/test/integrationTest/TestMaker/Test.java
> +            if(!data.equals("") && data != null)
The null check should be done before equals or it will throw an error on null

2022-04-19 23:51 UTC, ntrobin1 commented on configurator/src/test/org/picmg/test/integrationTest/TestMaker/Test.java
> +        public void fromJson(JsonObject jsonObject)
Per comment above, this would be better as constructor

2022-04-20 03:04 UTC, ntrobin1 approved these changes
Nice work.

2022-04-20 03:04 UTC, merged